# Generated by Django 3.1.1 on 2020-09-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=254, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
            },
        ),
        migrations.CreateModel(
            name='ExaminationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(verbose_name='试题')),
            ],
            options={
                'verbose_name': '考试试题',
                'verbose_name_plural': '考试试题',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_paper_name', models.CharField(max_length=254, verbose_name='试卷名')),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_choice', models.CharField(max_length=1, verbose_name='选项')),
                ('select_content', models.TextField(verbose_name='选项内容')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.examinationquestion', verbose_name='考试试题')),
            ],
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.select', verbose_name='答案'),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.testpaper'),
        ),
    ]
