# Generated by Django 3.1.1 on 2020-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_exam_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(null=True, to='teacher.ExaminationQuestion', verbose_name='试题'),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='answer',
            field=models.CharField(max_length=1, verbose_name='答案'),
        ),
    ]
