# Generated by Django 3.1.1 on 2020-09-21 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huser', '0001_initial'),
        ('teacher', '0004_examinationquestion_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='hclass',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='huser.hclass', verbose_name='班级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='huser.huser', verbose_name='教师'),
            preserve_default=False,
        ),
    ]
