# Generated by Django 3.1.1 on 2020-09-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0005_auto_20200921_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=54, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('video', models.URLField(verbose_name='视频')),
                ('audio', models.URLField(verbose_name='音频')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('correct_rate', models.FloatField(null=True, verbose_name='正确率')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam', verbose_name='考试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wrong', models.ManyToManyField(to='teacher.ExaminationQuestion', verbose_name='错题')),
            ],
        ),
    ]
